service: onboarding-bot
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  #  stage: dev
  region: eu-central-1

  environment:
    SLACK_ACCESS_TOKEN: ${env:SLACK_ACCESS_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

package:
  include:
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test
          method: get

  events:
    handler: handler.events
    events:
      - http:
          path: events
          method: post

  interactive:
    handler: handler.interactive
    events:
      - http:
          path: interactive
          method: post

  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: post

plugins:
  - serverless-offline
